- name: Install graphviz
  apt:
    name:
      - graphviz
      - graphviz-dev
    update_cache: true
  become: true

- name: Pre-clean bokeh directory and metadata to prevent nested installation
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - "{{ ansible_env.HOME }}/.local/lib/python3.10/site-packages/bokeh*"
  become: false

- name: Install caret dependent packages
  pip:
    requirements: "{{ requirements_path }}"
    executable: pip3
    extra_args: --force-reinstall
  become: false
  args:
    chdir: "{{ WORKSPACE_ROOT }}"
  when: pip_install | default('y') == 'y'
