rosdistro: humble
package: desktop
repository: http://packages.ros.org/ros2/ubuntu
keyserver: https://raw.githubusercontent.com/ros/rosdistro/master/ros.key
keyring_dest: /usr/share/keyrings/ros-archive-keyring.gpg
