- hosts: localhost
  connection: local
  become: false
  roles:
    - { role: lttng, tags: [lttng] }
    - { role: ros2, rosdistro: galactic, tags: [ros2] }
    - { role: ros-tracing, rosdistro: galactic, tags: [ros-tracing] }
    - { role: visualizer, tags: [visualizer] }
    - { role: caret, rosdistro: galactic, tags: [caret] }
